### ISSUE TITLE
先表达一下敬意，然后再提问

### ISSUE THREAD

**Issue by micln** [0x142857/node-zhihu-epub-generator#1]
我是从V2过来的==

我想请教一下大神 是如何生成mobi文件的？

我准备搞一个类似的东西 把 网页（稍后读）、RSS、公众号 的文章都推送给kindle，

希望能得到你的帮助

**Comment by egoist** [comment]
我是本地用 Calibre 手动 epub 转 mobi 的

P.S. 你说的这种东西已经有了， 狗耳朵、Kindle4Rss
